# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: 'Terminal 1'
    init: echo 'init script' # runs during prebuild
    command: echo 'start script'
  - name: 'Terminal 2'  
    # Instalamos un sistema gestor de paquetes
    init: npm install
    # Indicamos que se ejecute cada vez que empezemos un proyecto
    command: npm run dev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
